### ISSUE TITLE
Simple polygon triangles error!

### ISSUE THREAD

**Issue by sheiling** [jhasse/poly2tri#8]
When I using "poly2tri" to triangles my polygons, amlost of them can work fines! But, this polygon works invalid. 

1. The polygon image:
![传入ID所对应三角面剖分轮廓图](https://user-images.githubusercontent.com/15042542/66796212-92686400-ef39-11e9-8293-05c7e5869a7e.jpg)
2. triangles.dat using the demo format

[triangles.zip](https://github.com/jhasse/poly2tri/files/3727201/triangles.zip)

3. Tringle result: 
![捕获](https://user-images.githubusercontent.com/15042542/66796384-115d9c80-ef3a-11e9-8431-18e35bafbc0e.PNG)

Can your help me,thanks!

**Comment by praveenagrawal** [comment]
Hi 
Even I am facing a similar error while trying to triangulate a 2D contour in the shape of letter 'D'. The error I am facing is exactly like the above example where two points are wrongly generated on the bottom left and bottom right.

**Comment by sheiling** [comment]
Hi,when I searched some tips about this problem,but not got a direct answer.
So I using " ear cut " make the polygon triangle right!



---Original---

**Comment by Myszkoj** [comment]
Hello, 
I have found out that sometimes generated triangles use head_ and tail_ points from the SweepContext.
Any idea why?

**Comment by pierre-dejoue** [comment]
Hello,

I investigated this issue. It turns out that the input polygon isn't simple, which is a requirement of the input of `poly2tri` (see README for more information.)

More precisely, the following edges taken from the original input are self-intersecting:

```
628 511
628 508
632 508
610 509
```

This can be seen by zooming in on that area:

`./p2t.exe ./testbed/data/triangles-issue-8.dat 620 510 40`
![non-simple-polygon](https://user-images.githubusercontent.com/3603963/166198774-8dc802e8-5c1a-4c06-a999-a5cdd40238d7.png)

**Comment by pierre-dejoue** [comment]
In addition to my previous post, if we move one of the points to make the polygon simple, then the triangulation works properly.

Moving point `628 508` to `628 509`:
![make-it-simple](https://user-images.githubusercontent.com/3603963/166199138-a490bfbd-c2ad-48d9-bc61-5110a732bfad.png)

Whole solution with the patched polygon:
![full-polygon-with-patch](https://user-images.githubusercontent.com/3603963/166199191-3f55a8ce-f3d5-4f7f-b79c-f9c4a071532a.png)
